/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ReferrerRouteRouteImport } from './routes/referrer/route'
import { Route as AuthenticatedAlumniRouteImport } from './routes/_authenticated/alumni'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ReferrerInboxRouteImport } from './routes/referrer/inbox'
import { Route as ReferrerProfileRouteImport } from './routes/referrer/profile'
import { Route as ApiPublicN8nCompaniesRouteImport } from './routes/api/public/n8n/companies'
import { Route as ApiPublicN8nRescoreRouteImport } from './routes/api/public/n8n/rescore'
import { Route as ApiPublicN8nPostingsClassificationRouteImport } from './routes/api/public/n8n/postings/classification'
import { Route as ApiPublicN8nPostingsUpsertRouteImport } from './routes/api/public/n8n/postings/upsert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferrerRouteRoute = ReferrerRouteRouteImport.update({
  id: '/referrer',
  path: '/referrer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlumniRoute = AuthenticatedAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ReferrerInboxRoute = ReferrerInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ReferrerRouteRoute,
} as any)
const ReferrerProfileRoute = ReferrerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReferrerRouteRoute,
} as any)
const ApiPublicN8nCompaniesRoute = ApiPublicN8nCompaniesRouteImport.update({
  id: '/api/public/n8n/companies',
  path: '/api/public/n8n/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nRescoreRoute = ApiPublicN8nRescoreRouteImport.update({
  id: '/api/public/n8n/rescore',
  path: '/api/public/n8n/rescore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nPostingsClassificationRoute =
  ApiPublicN8nPostingsClassificationRouteImport.update({
    id: '/api/public/n8n/postings/classification',
    path: '/api/public/n8n/postings/classification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nPostingsUpsertRoute =
  ApiPublicN8nPostingsUpsertRouteImport.update({
    id: '/api/public/n8n/postings/upsert',
    path: '/api/public/n8n/postings/upsert',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/referrer': typeof ReferrerRouteRouteWithChildren
  '/alumni': typeof AuthenticatedAlumniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrer/inbox': typeof ReferrerInboxRoute
  '/referrer/profile': typeof ReferrerProfileRoute
  '/api/public/n8n/companies': typeof ApiPublicN8nCompaniesRoute
  '/api/public/n8n/rescore': typeof ApiPublicN8nRescoreRoute
  '/api/public/n8n/postings/classification': typeof ApiPublicN8nPostingsClassificationRoute
  '/api/public/n8n/postings/upsert': typeof ApiPublicN8nPostingsUpsertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/referrer': typeof ReferrerRouteRouteWithChildren
  '/alumni': typeof AuthenticatedAlumniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrer/inbox': typeof ReferrerInboxRoute
  '/referrer/profile': typeof ReferrerProfileRoute
  '/api/public/n8n/companies': typeof ApiPublicN8nCompaniesRoute
  '/api/public/n8n/rescore': typeof ApiPublicN8nRescoreRoute
  '/api/public/n8n/postings/classification': typeof ApiPublicN8nPostingsClassificationRoute
  '/api/public/n8n/postings/upsert': typeof ApiPublicN8nPostingsUpsertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/referrer': typeof ReferrerRouteRouteWithChildren
  '/_authenticated/alumni': typeof AuthenticatedAlumniRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/referrer/inbox': typeof ReferrerInboxRoute
  '/referrer/profile': typeof ReferrerProfileRoute
  '/api/public/n8n/companies': typeof ApiPublicN8nCompaniesRoute
  '/api/public/n8n/rescore': typeof ApiPublicN8nRescoreRoute
  '/api/public/n8n/postings/classification': typeof ApiPublicN8nPostingsClassificationRoute
  '/api/public/n8n/postings/upsert': typeof ApiPublicN8nPostingsUpsertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/referrer'
    | '/alumni'
    | '/dashboard'
    | '/feed'
    | '/preferences'
    | '/profile'
    | '/referrer/inbox'
    | '/referrer/profile'
    | '/api/public/n8n/companies'
    | '/api/public/n8n/rescore'
    | '/api/public/n8n/postings/classification'
    | '/api/public/n8n/postings/upsert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/referrer'
    | '/alumni'
    | '/dashboard'
    | '/feed'
    | '/preferences'
    | '/profile'
    | '/referrer/inbox'
    | '/referrer/profile'
    | '/api/public/n8n/companies'
    | '/api/public/n8n/rescore'
    | '/api/public/n8n/postings/classification'
    | '/api/public/n8n/postings/upsert'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/referrer'
    | '/_authenticated/alumni'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/preferences'
    | '/_authenticated/profile'
    | '/referrer/inbox'
    | '/referrer/profile'
    | '/api/public/n8n/companies'
    | '/api/public/n8n/rescore'
    | '/api/public/n8n/postings/classification'
    | '/api/public/n8n/postings/upsert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ReferrerRouteRoute: typeof ReferrerRouteRouteWithChildren
  ApiPublicN8nCompaniesRoute: typeof ApiPublicN8nCompaniesRoute
  ApiPublicN8nRescoreRoute: typeof ApiPublicN8nRescoreRoute
  ApiPublicN8nPostingsClassificationRoute: typeof ApiPublicN8nPostingsClassificationRoute
  ApiPublicN8nPostingsUpsertRoute: typeof ApiPublicN8nPostingsUpsertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrer': {
      id: '/referrer'
      path: '/referrer'
      fullPath: '/referrer'
      preLoaderRoute: typeof ReferrerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alumni': {
      id: '/_authenticated/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AuthenticatedAlumniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/referrer/inbox': {
      id: '/referrer/inbox'
      path: '/inbox'
      fullPath: '/referrer/inbox'
      preLoaderRoute: typeof ReferrerInboxRouteImport
      parentRoute: typeof ReferrerRouteRoute
    }
    '/referrer/profile': {
      id: '/referrer/profile'
      path: '/profile'
      fullPath: '/referrer/profile'
      preLoaderRoute: typeof ReferrerProfileRouteImport
      parentRoute: typeof ReferrerRouteRoute
    }
    '/api/public/n8n/companies': {
      id: '/api/public/n8n/companies'
      path: '/api/public/n8n/companies'
      fullPath: '/api/public/n8n/companies'
      preLoaderRoute: typeof ApiPublicN8nCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/rescore': {
      id: '/api/public/n8n/rescore'
      path: '/api/public/n8n/rescore'
      fullPath: '/api/public/n8n/rescore'
      preLoaderRoute: typeof ApiPublicN8nRescoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/postings/classification': {
      id: '/api/public/n8n/postings/classification'
      path: '/api/public/n8n/postings/classification'
      fullPath: '/api/public/n8n/postings/classification'
      preLoaderRoute: typeof ApiPublicN8nPostingsClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/postings/upsert': {
      id: '/api/public/n8n/postings/upsert'
      path: '/api/public/n8n/postings/upsert'
      fullPath: '/api/public/n8n/postings/upsert'
      preLoaderRoute: typeof ApiPublicN8nPostingsUpsertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlumniRoute: typeof AuthenticatedAlumniRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlumniRoute: AuthenticatedAlumniRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ReferrerRouteRouteChildren {
  ReferrerInboxRoute: typeof ReferrerInboxRoute
  ReferrerProfileRoute: typeof ReferrerProfileRoute
}

const ReferrerRouteRouteChildren: ReferrerRouteRouteChildren = {
  ReferrerInboxRoute: ReferrerInboxRoute,
  ReferrerProfileRoute: ReferrerProfileRoute,
}

const ReferrerRouteRouteWithChildren = ReferrerRouteRoute._addFileChildren(
  ReferrerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ReferrerRouteRoute: ReferrerRouteRouteWithChildren,
  ApiPublicN8nCompaniesRoute: ApiPublicN8nCompaniesRoute,
  ApiPublicN8nRescoreRoute: ApiPublicN8nRescoreRoute,
  ApiPublicN8nPostingsClassificationRoute:
    ApiPublicN8nPostingsClassificationRoute,
  ApiPublicN8nPostingsUpsertRoute: ApiPublicN8nPostingsUpsertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
